name = input("Enter your name: ")
print("")
print("Game #1:")
opponent1_name = input("Opponent's Name: ")
game1_my_pts = int(input("Your Points: "))
game1_opponent_pts = int(input("Opponent's Points: "))

print("")
print("Game #2:")
opponent2_name = input("Opponent's Name: ")
game2_my_pts = int(input("Your Points: "))
game2_opponent_pts = int(input("Opponent's Points: "))

print("")
print("Game #3:")
opponent3_name = input("Opponent's Name: ")
game3_my_pts = int(input("Your Points: "))
game3_opponent_pts = int(input("Opponent's Points: "))

print("")
print("Game #4:")
opponent4_name = input("Opponent's Name: ")
game4_my_pts = int(input("Your Points: "))
game4_opponent_pts = int(input("Opponent's Points: "))

print("")
print("Game #5:")
opponent5_name = input("Opponent's Name: ")
game5_my_pts = int(input("Your Points: "))
game5_opponent_pts = int(input("Opponent's Points: "))

my_pts_total = game1_my_pts + game2_my_pts + game3_my_pts + game4_my_pts + game5_my_pts
opponent_pts_total = game1_opponent_pts + game2_opponent_pts + game3_opponent_pts + game4_opponent_pts + game5_opponent_pts
my_percentage_total_pts = my_pts_total/(36*5)


print("")
print("")
print("Dots and Boxes Score Tracker")
print("")
print(f"Player's Name: {name}")
print("")
print(f"{'Opponent':<11}{'Your Points':>11}{'Opponent Points':>20}{'Box %':>12}")
print("======================================================")
print(f"{opponent1_name:<11}{game1_my_pts:>11}{game1_opponent_pts:>20}{(game1_my_pts/36):>12.2%}")
print(f"{opponent2_name:<11}{game2_my_pts:>11}{game2_opponent_pts:>20}{(game2_my_pts/36):>12.2%}")
print(f"{opponent3_name:<11}{game3_my_pts:>11}{game3_opponent_pts:>20}{(game3_my_pts/36):>12.2%}")
print(f"{opponent4_name:<11}{game4_my_pts:>11}{game4_opponent_pts:>20}{(game4_my_pts/36):>12.2%}")
print(f"{opponent5_name:<11}{game5_my_pts:>11}{game5_opponent_pts:>20}{(game5_my_pts/36):>12.2%}")

print("")
print("Summary:")
print(f"Total Points: {my_pts_total}")
print(f"Total Opponent Points: {opponent_pts_total}")
print(f"Percentage Points Recieved: {my_percentage_total_pts:.2%}")
