print("Welcome to the School Resources Assesment Program!")
print("")
print("Location: 85 Moatfield Drive")
print("")
print("1. Water Fountains: ")
water_fountains = int(input("- Enter the number of water fountains: "))
water_fountain_location = input("- Enter the location of the water fountains (seperated by commas): ")
water_fountain_condition = input("- Describe the condition of the water fountains: ")


print("")
print("2. Restrooms: ")
restrooms = int(input("- Enter the number of restrooms: "))
restroom_location = input("- Enter the location of the restrooms (seperated by commas): ")
restroom_cleanliness = input("- Describe the cleanliness of the restrooms: ")

print("")
print("3. Cafeteria: ")
cafeteria_seating = int(input("- Enter the seating capacity of the cafeteria: "))
cafeteria_attendance = int(input("- Enter the average daily attendace in the cafeteria: "))
cafeteria_condition = input("- Describe the condition of the cafeteria: ")

print("")
print("4. Classrooms: ")
classrooms = int(input("- Enter the total number of classrooms: "))

water_fountains_per_classroom = water_fountains/classrooms
restrooms_per_classroom = restrooms/classrooms

print("")
print("")
print("*Data Collected*")
print("")
print("1. Water Fountains: ")
print(f"- Number of Water Fountains: {water_fountains}")
print(f"- Locations: {water_fountain_location}")
print(f"- Conditions: {water_fountain_condition}")
print("")
print("2. Restrooms: ")
print(f"- Number of Restrooms: {restrooms}")
print(f"- Locations: {restroom_location}")
print(f"- Cleanliness: {restroom_cleanliness}")
print("")
print("3. Cafeteria: ")
print(f"- Seating Capacity: {cafeteria_seating} ")
print(f"- Average Daily Attendance: {cafeteria_attendance}")
print(f"- Condition: {cafeteria_condition}")
print("")
print("4. Classrooms:")
print(f"- Total Number of Classroms: {classrooms}")
print(f"- Number of Water Fountains per Classroom: {round(water_fountains_per_classroom)}")
print(f"- Number of Restrooms per Classroom: {round(restrooms_per_classroom)}")